#!/usr/bin/env bash
# This script was generated by rargs 0.0.0 (https://rargs.cloudbridge.uy)
# Modifying it manually is not recommended

if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
  printf "bash version 4 or higher is required\n" >&2
  exit 1
fi

if [[ -n "${DEBUG:-}" ]]; then
  set -x
fi
set -e


normalize_input() {
  local arg flags

  while [[ $# -gt 0 ]]; do
    arg="$1"
    if [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^-([a-zA-Z0-9][a-zA-Z0-9]+)$ ]]; then
      flags="${BASH_REMATCH[1]}"
      for ((i = 0; i < ${#flags}; i++)); do
        input+=("-${flags:i:1}")
      done
    else
      input+=("$arg")
    fi

    shift
  done
}

inspect_args() {
  prefix="rargs_"
  args="$(set | grep ^$prefix || true)"
  if [[ -n "$args" ]]; then
    echo
    echo args:
    for var in $args; do
      echo "- $var" | sed 's/=/ = /g'
    done
  fi

  if ((${#deps[@]})); then
    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
    echo
    echo deps:
    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
  fi

  if ((${#other_args[@]})); then
    echo
    echo other_args:
    echo "- \${other_args[*]} = ${other_args[*]}"
    for i in "${!other_args[@]}"; do
      echo "- \${other_args[$i]} = ${other_args[$i]}"
    done
  fi
}

set -eo pipefail
ROOT_DIRECTORY="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
DEMO_NAME="${DEMO_NAME:-"cross-region-cross-account-rds-backups"}"
primary="aws --profile cloudbridge-dba-primary"

version() {
  echo "0.1.0"
}
usage() {
  printf "Handle the cold-start resources\n"
  printf "\n\033[4m%s\033[0m\n" "Usage:"
  printf "  cold-start [OPTIONS] [COMMAND] [COMMAND_OPTIONS]\n"
  printf "  cold-start -h|--help\n"
  printf "  cold-start -v|--version\n"
  printf "\n\033[4m%s\033[0m\n" "Commands:"
  cat <<EOF
  create ..... Deploy the cold-start resources using CloudFormation
  destroy .... Destroys the cold-start resources using CloudFormation
  status ..... Get the status of the deployed cold-start resources
  track ...... Track the update of a CloudFormation template
  update ..... Update the cold-start resources using CloudFormation
EOF

  printf "\n\033[4m%s\033[0m\n" "Options:"
  printf "  -h --help\n"
  printf "    Print help\n"
  printf "  -v --version\n"
  printf "    Print version\n"
}

parse_arguments() {
  while [[ $# -gt 0 ]]; do
    case "${1:-}" in
      -v|--version)
        version
        exit
        ;;
      -h|--help)
        usage
        exit
        ;;
      *)
        break
        ;;
    esac
  done
  action="${1:-}"

  case $action in
    create)
      action="create"
      input=("${input[@]:1}")
      ;;
    destroy)
      action="destroy"
      input=("${input[@]:1}")
      ;;
    status)
      action="status"
      input=("${input[@]:1}")
      ;;
    track)
      action="track"
      input=("${input[@]:1}")
      ;;
    update)
      action="update"
      input=("${input[@]:1}")
      ;;
    -h|--help)
      usage
      exit
      ;;
    "")
      ;;
    *)
      printf "\e[31m%s\e[33m%s\e[31m\e[0m\n\n" "Invalid command: " "$action" >&2
      exit 1
      ;;
  esac
}
create_usage() {
  printf "Deploy the cold-start resources using CloudFormation\n"

  printf "\n\033[4m%s\033[0m\n" "Usage:"
  printf "  create [OPTIONS]\n"
  printf "  create -h|--help\n"

  printf "\n\033[4m%s\033[0m\n" "Options:"
  printf "  -e --environment [<ENVIRONMENT>]\n"
  printf "    The name of the environment to depoy to.\n"
  printf "    [@default dev]\n"
  printf "  -p --parameters [<PARAMETERS>]\n"
  printf "    The name of the parameters file to use.\n"
  printf "  -s --stack-name [<STACK-NAME>]\n"
  printf "    The name of the stack to use.\n"
  printf "  -t --template [<TEMPLATE>]\n"
  printf "    The name of the template to use.\n"
  printf "  --no-track\n"
  printf "    Don't track update changes.\n"
  printf "  -h --help\n"
  printf "    Print help\n"
}
parse_create_arguments() {
  while [[ $# -gt 0 ]]; do
    case "${1:-}" in
      -h|--help)
        create_usage
        exit
        ;;
      *)
        break
        ;;
    esac
  done

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --no-track)
        rargs_no_track=1
        shift
        ;;
      -e | --environment)
        rargs_environment="$2"
        shift 2
        ;;
      -p | --parameters)
        rargs_parameters="$2"
        shift 2
        ;;
      -s | --stack-name)
        rargs_stack_name="$2"
        shift 2
        ;;
      -t | --template)
        rargs_template="$2"
        shift 2
        ;;
      -?*)
        printf "\e[31m%s\e[33m%s\e[31m\e[0m\n\n" "Invalid option: " "$key" >&2
        exit 1
        ;;
      *)
        if [[ "$key" == "" ]]; then
          break
        fi
        printf "\e[31m%s\e[33m%s\e[31m\e[0m\n\n" "Invalid argument: " "$key" >&2
        exit 1
        ;;
    esac
  done
}
# Deploy the cold-start resources using CloudFormation
create() {
  local rargs_no_track
  local rargs_environment
  local rargs_parameters
  local rargs_stack_name
  local rargs_template
  # Parse command arguments
  parse_create_arguments "$@"

  
    
  if [[ -z "$rargs_environment" ]]; then
    rargs_environment="dev"
  fi
    
	if [[ -z "$rargs_stack_name" ]]; then
		rargs_stack_name="$DEMO_NAME-$rargs_environment"
	fi
	if [[ -z "$rargs_template" ]]; then
		rargs_template="$ROOT_DIRECTORY/../cold-start-cf-template.yaml"
	fi
	if [[ -z "$rargs_parameters" ]]; then
		rargs_parameters="$ROOT_DIRECTORY/../cold-start-parameters.$rargs_environment.json"
	fi
	echo "Attempting to create stack $rargs_stack_name" >&2
	if ! $primary cloudformation create-stack \
		--stack-name "$rargs_stack_name" \
		--template-body "file://$rargs_template" \
		--parameters "file://$rargs_parameters" \
		--capabilities CAPABILITY_IAM; then
		update \
			--environment "$rargs_environment" \
			--stack-name "$rargs_stack_name" \
			--template "$rargs_template" \
			--parameters "$rargs_parameters" \
			--no-track
	fi
	if [[ -z "$rargs_no_track" ]]; then
		__track_cf_template "$rargs_stack_name"
	fi
	exit $?
}
destroy_usage() {
  printf "Destroys the cold-start resources using CloudFormation\n"

  printf "\n\033[4m%s\033[0m\n" "Usage:"
  printf "  destroy [OPTIONS]\n"
  printf "  destroy -h|--help\n"

  printf "\n\033[4m%s\033[0m\n" "Options:"
  printf "  -e --environment [<ENVIRONMENT>]\n"
  printf "    The name of the environment to depoy to.\n"
  printf "    [@default dev]\n"
  printf "  -s --stack-name [<STACK-NAME>]\n"
  printf "    The name of the stack to use.\n"
  printf "  -h --help\n"
  printf "    Print help\n"
}
parse_destroy_arguments() {
  while [[ $# -gt 0 ]]; do
    case "${1:-}" in
      -h|--help)
        destroy_usage
        exit
        ;;
      *)
        break
        ;;
    esac
  done

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      -e | --environment)
        rargs_environment="$2"
        shift 2
        ;;
      -s | --stack-name)
        rargs_stack_name="$2"
        shift 2
        ;;
      -?*)
        printf "\e[31m%s\e[33m%s\e[31m\e[0m\n\n" "Invalid option: " "$key" >&2
        exit 1
        ;;
      *)
        if [[ "$key" == "" ]]; then
          break
        fi
        printf "\e[31m%s\e[33m%s\e[31m\e[0m\n\n" "Invalid argument: " "$key" >&2
        exit 1
        ;;
    esac
  done
}
# Destroys the cold-start resources using CloudFormation
destroy() {
  local rargs_environment
  local rargs_stack_name
  # Parse command arguments
  parse_destroy_arguments "$@"

  
    
  if [[ -z "$rargs_environment" ]]; then
    rargs_environment="dev"
  fi
    
	if [[ -z "$rargs_stack_name" ]]; then
		rargs_stack_name="$DEMO_NAME-$rargs_environment"
	fi
	$primary cloudformation delete-stack \
		--stack-name cross-region-cross-account-rds-backups-dev
}
status_usage() {
  printf "Get the status of the deployed cold-start resources\n"

  printf "\n\033[4m%s\033[0m\n" "Usage:"
  printf "  status [OPTIONS]\n"
  printf "  status -h|--help\n"

  printf "\n\033[4m%s\033[0m\n" "Options:"
  printf "  -e --environment [<ENVIRONMENT>]\n"
  printf "    The name of the environment to depoy to.\n"
  printf "    [@default dev]\n"
  printf "  -s --stack-name [<STACK-NAME>]\n"
  printf "    The name of the stack to use.\n"
  printf "  -h --help\n"
  printf "    Print help\n"
}
parse_status_arguments() {
  while [[ $# -gt 0 ]]; do
    case "${1:-}" in
      -h|--help)
        status_usage
        exit
        ;;
      *)
        break
        ;;
    esac
  done

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      -e | --environment)
        rargs_environment="$2"
        shift 2
        ;;
      -s | --stack-name)
        rargs_stack_name="$2"
        shift 2
        ;;
      -?*)
        printf "\e[31m%s\e[33m%s\e[31m\e[0m\n\n" "Invalid option: " "$key" >&2
        exit 1
        ;;
      *)
        if [[ "$key" == "" ]]; then
          break
        fi
        printf "\e[31m%s\e[33m%s\e[31m\e[0m\n\n" "Invalid argument: " "$key" >&2
        exit 1
        ;;
    esac
  done
}
# Get the status of the deployed cold-start resources
status() {
  local rargs_environment
  local rargs_stack_name
  # Parse command arguments
  parse_status_arguments "$@"

  
    
  if [[ -z "$rargs_environment" ]]; then
    rargs_environment="dev"
  fi
    
	if [[ -z "$rargs_stack_name" ]]; then
		rargs_stack_name="$DEMO_NAME-$rargs_environment"
	fi
	{
		echo "---"
		echo "Name: $rargs_stack_name"
		echo "Status: $(
			$primary cloudformation describe-stacks \
				--stack-name "$rargs_stack_name" \
				--query "Stacks[0].StackStatus" \
				--output text
		)"
		echo "Parameters: "
		$primary cloudformation describe-stacks \
			--stack-name "$rargs_stack_name" \
			--query "Stacks[0].Parameters" | yq -P
		$primary cloudformation describe-stack-resources \
			--stack-name "$rargs_stack_name" | yq -P
		echo "Outputs: "
		$primary cloudformation describe-stacks \
			--stack-name "$rargs_stack_name" \
			--query "Stacks[0].Outputs" | yq -P
		echo "..."
	} | yq -P
}
track_usage() {
  printf "Track the update of a CloudFormation template\n"

  printf "\n\033[4m%s\033[0m\n" "Usage:"
  printf "  track [OPTIONS]\n"
  printf "  track -h|--help\n"

  printf "\n\033[4m%s\033[0m\n" "Options:"
  printf "  -e --environment [<ENVIRONMENT>]\n"
  printf "    The name of the environment to depoy to.\n"
  printf "    [@default dev]\n"
  printf "  -s --stack-name [<STACK-NAME>]\n"
  printf "    The name of the stack to use.\n"
  printf "  -h --help\n"
  printf "    Print help\n"
}
parse_track_arguments() {
  while [[ $# -gt 0 ]]; do
    case "${1:-}" in
      -h|--help)
        track_usage
        exit
        ;;
      *)
        break
        ;;
    esac
  done

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      -e | --environment)
        rargs_environment="$2"
        shift 2
        ;;
      -s | --stack-name)
        rargs_stack_name="$2"
        shift 2
        ;;
      -?*)
        printf "\e[31m%s\e[33m%s\e[31m\e[0m\n\n" "Invalid option: " "$key" >&2
        exit 1
        ;;
      *)
        if [[ "$key" == "" ]]; then
          break
        fi
        printf "\e[31m%s\e[33m%s\e[31m\e[0m\n\n" "Invalid argument: " "$key" >&2
        exit 1
        ;;
    esac
  done
}
# Track the update of a CloudFormation template
track() {
  local rargs_environment
  local rargs_stack_name
  # Parse command arguments
  parse_track_arguments "$@"

  
    
  if [[ -z "$rargs_environment" ]]; then
    rargs_environment="dev"
  fi
    
	local EXIT_STATUS
	EXIT_STATUS=0
	tmp="$(mktemp)"
	if [[ -z "$rargs_stack_name" ]]; then
		rargs_stack_name="$DEMO_NAME-$rargs_environment"
	fi
	while True; do
		status="$(
			$primary cloudformation describe-stacks \
				--stack-name "$rargs_stack_name" \
				--query 'Stacks[].StackStatus' | yq -r '.[]'
		)"
		case "$status" in
		UPDATE_COMPLETE | CREATE_COMPLETE)
			echo "Deployment complete"
			break
			;;
		UPDATE_FAILED | CREATE_FAILED | UPDATE_ROLLBACK_COMPLETE | ROLLBACK_COMPLETE | ROLLBACK_FAILED)
			echo "Deployment failed"
			EXIT_STATUS=1
			break
			;;
		DELETE_COMPLETE | DELETE_FAILED)
			echo "Deployment failed and needs to be deleted"
			EXIT_STATUS=2
			DESTROY=1
			break
			;;
		esac
		$primary cloudformation describe-stack-events \
			--stack-name "$1" \
			--query 'StackEvents[].{LogicalResourceId: LogicalResourceId, ResourceStatus: ResourceStatus, ResourceStatusReason: ResourceStatusReason}' | yq '.[] | .LogicalResourceId + "|" + .ResourceStatus + "|" + .ResourceStatusReason' |
			column -t -s'|' |
			sort -r |
			while read -r line; do
				id="$(base64 <<<"$(echo -n "$line" | tr -d ' ')")"
				if ! grep -q "$id" "$tmp"; then
					echo "$id" >>"$tmp"
					echo "$line"
				fi
			done
		sleep 5
	done
	if [[ "$DESTROY" == 1 ]]; then
		destroy -s "rargs_stack_name"
	fi
	return $EXIT_STATUS
}
update_usage() {
  printf "Update the cold-start resources using CloudFormation\n"

  printf "\n\033[4m%s\033[0m\n" "Usage:"
  printf "  update [OPTIONS]\n"
  printf "  update -h|--help\n"

  printf "\n\033[4m%s\033[0m\n" "Options:"
  printf "  -e --environment [<ENVIRONMENT>]\n"
  printf "    The name of the environment to depoy to.\n"
  printf "    [@default dev]\n"
  printf "  -p --parameters [<PARAMETERS>]\n"
  printf "    The name of the parameters file to use.\n"
  printf "  -s --stack-name [<STACK-NAME>]\n"
  printf "    The name of the stack to use.\n"
  printf "  -t --template [<TEMPLATE>]\n"
  printf "    The name of the template to use.\n"
  printf "  --no-track\n"
  printf "    Don't track update changes.\n"
  printf "  -h --help\n"
  printf "    Print help\n"
}
parse_update_arguments() {
  while [[ $# -gt 0 ]]; do
    case "${1:-}" in
      -h|--help)
        update_usage
        exit
        ;;
      *)
        break
        ;;
    esac
  done

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --no-track)
        rargs_no_track=1
        shift
        ;;
      -e | --environment)
        rargs_environment="$2"
        shift 2
        ;;
      -p | --parameters)
        rargs_parameters="$2"
        shift 2
        ;;
      -s | --stack-name)
        rargs_stack_name="$2"
        shift 2
        ;;
      -t | --template)
        rargs_template="$2"
        shift 2
        ;;
      -?*)
        printf "\e[31m%s\e[33m%s\e[31m\e[0m\n\n" "Invalid option: " "$key" >&2
        exit 1
        ;;
      *)
        if [[ "$key" == "" ]]; then
          break
        fi
        printf "\e[31m%s\e[33m%s\e[31m\e[0m\n\n" "Invalid argument: " "$key" >&2
        exit 1
        ;;
    esac
  done
}
# Update the cold-start resources using CloudFormation
update() {
  local rargs_no_track
  local rargs_environment
  local rargs_parameters
  local rargs_stack_name
  local rargs_template
  # Parse command arguments
  parse_update_arguments "$@"

  
    
  if [[ -z "$rargs_environment" ]]; then
    rargs_environment="dev"
  fi
    
	if [[ -z "$rargs_stack_name" ]]; then
		rargs_stack_name="$DEMO_NAME-$rargs_environment"
	fi
	if [[ -z "$rargs_template" ]]; then
		rargs_template="$ROOT_DIRECTORY/../cold-start-cf-template.yaml"
	fi
	if [[ -z "$rargs_parameters" ]]; then
		rargs_parameters="$ROOT_DIRECTORY/../cold-start-parameters.$rargs_environment.json"
	fi
	change_set_name="$rargs_stack_name-change-set-$(date +%s)"
	echo "Creating change set $change_set_name" >&2
	$primary cloudformation create-change-set \
		--stack-name "$rargs_stack_name" \
		--template-body "file://$rargs_template" \
		--parameters "file://$rargs_parameters" \
		--change-set-name "$change_set_name" \
		--capabilities CAPABILITY_NAMED_IAM
	echo "Waiting for change set to be created" >&2
	$primary cloudformation wait change-set-create-complete \
		--stack-name "$rargs_stack_name" \
		--change-set-name "$change_set_name"
	echo "Change set details" >&2
	$primary cloudformation describe-change-set \
		--stack-name "$rargs_stack_name" \
		--change-set-name "$change_set_name" | yq -P '.Changes'
	echo "Executing change set $change_set_name" >&2
	$primary cloudformation execute-change-set \
		--stack-name "$rargs_stack_name" \
		--change-set-name "$change_set_name"
	if [[ -z "$rargs_no_track" ]]; then
		__track_cf_template "$rargs_stack_name"
	fi
	exit $?
}

run() {
  declare -A deps=()
  declare -a input=()
  normalize_input "$@"
  parse_arguments "${input[@]}"
  # Call the right command action
  case "$action" in
    "create")
      create "${input[@]}"
      exit
      ;;
    "destroy")
      destroy "${input[@]}"
      exit
      ;;
    "status")
      status "${input[@]}"
      exit
      ;;
    "track")
      track "${input[@]}"
      exit
      ;;
    "update")
      update "${input[@]}"
      exit
      ;;
    "")
      printf "\e[31m%s\e[33m%s\e[31m\e[0m\n\n" "Missing command. Select one of " "create, destroy, status, track, update" >&2
      usage >&2
      exit 1
      ;;
    
  esac
}

run "$@"
