---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Este Template de CloudFormation contiene los recursos iniciales necesarios para la prueba de concepto."

Parameters:
  AwsRegion:
    Description: Region de origen de AWS en la cuenta principal
    Type: String
  PrimaryAccount:
    Description: Cuenta principal para el almacenado de Snapshots de RDS
    Type: String
Resources:
  SharedSnapshotEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Regla de EventBridge para la detección de eventos generados al momento de compartir un snapshot.
      EventPattern:
        source: ["atos.rds"]
        detail-type: ["RDS DB Shared Snapshot Event"]
        account:
          - !Ref PrimaryAccount
        region:
          - !Ref AwsRegion
        detail:
          SourceType: ["SNAPSHOT"]
          EventID: ["CROSS-ACCOUNT-SHARED-SNAPSHOT"]
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt: [SnapshotLambdaFunction, Arn]
          Id: SnapshotLambdaTarget

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - rds:DescribeDBSnapshots
                  - rds:CopyDBSnapshot
                  - rds:AddTagsToResource
                  - rds:ModifyDBSnapshotAttribute
                Resource: "*"
              - Effect: Allow
                Action:
                  - kms:CreateGrant
                  - kms:DescribeKey
                  - kms:Encrypt
                  - kms:ReEncrypt*
                  - kms:GenerateDataKey*
                  - kms:DescribeKey
                Resource: "*"

  SnapshotLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn: SecondaryKmsKey
    Properties:
      Handler: index.handler
      Role:
        Fn::GetAtt: [LambdaExecutionRole, Arn]
      Code:
        ZipFile: |
          ${LAMBDA_CONTENTS}
      Runtime: python3.8
      Environment:
        Variables:
          PRIMARY_ACCOUNT: !Ref PrimaryAccount
          KMS_KEY_ID: !Ref SecondaryKmsKey
      Timeout: 30

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: SnapshotLambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt: [SharedSnapshotEventRule, Arn]

  SecondaryKmsKey:
    Type: "AWS::KMS::Key"
    Properties:
      Description: "Llave KMS para copiar los snapshots creados por RDS."
      MultiRegion: true
      KeyPolicy:
        Version: "2012-10-17"
        Id: "Id-Kms-1"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: "Permitir el uso con RDS"
            Effect: "Allow"
            Principal:
              Service: "rds.amazonaws.com"
            Action:
              - "kms:CreateGrant"
              - "kms:ListGrant"
              - "kms:RevokeGrant"
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"
          - Sid: "Permitir a la funcion lambda del uso de la llave"
            Effect: "Allow"
            Principal:
              AWS: !GetAtt LambdaExecutionRole.Arn
            Action:
              - "kms:CreateGrant"
              - "kms:ListGrant"
              - "kms:RevokeGrant"
              - "kms:DescribeKey"
              - "kms:Encrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"
            Condition: { "Bool": { "kms:GrantIsForAWSResource": true } }
