---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Este Template de CloudFormation contiene los recursos iniciales necesarios para la prueba de concepto."

Parameters:
  AwsRegion:
    Description: Region de origen de AWS en la cuenta principal
    Type: String
  PrincipalKmsKeyArn:
    Description: Llave KMS Multi-Region creada en la cuenta principal compartida con la region de contingencia
    Type: String
  LambdaExecutionRoleArn:
    Description: Rol de lambda que debe tener accesso a la Replica de KMS.
    Type: String
  CrossAccount:
    Description: Cuenta de contingencia para el almacenado de Snapshots de RDS
    Type: String
Resources:
  CopySnapshotEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Regla de EventBridge para la gestion de snapshots automaticos.
      EventPattern:
        source: ["aws.rds"]
        detail-type: ["RDS DB Snapshot Event"]
        account:
          - !Sub ${AWS::AccountId}
        detail:
          SourceType: ["SNAPSHOT"]
          EventID: ["RDS-EVENT-0060"]
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt: [SnapshotLambdaFunction, Arn]
          Id: SnapshotLambdaTarget

  SnapshotLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !Ref LambdaExecutionRoleArn
      Code:
        ZipFile: |
          ${LAMBDA_CONTENTS}
      Runtime: python3.8
      Environment:
        Variables:
          CROSS_ACCOUNT: !Ref CrossAccount
      Timeout: 30

  CopyPermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: SnapshotLambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt: [CopySnapshotEventRule, Arn]

  PrincipalKmsKeyReplica:
    Type: "AWS::KMS::ReplicaKey"
    Properties:
      PrimaryKeyArn: !Ref PrincipalKmsKeyArn
      Description: "Replica de PrincipalKmsKey en region de contingencia"
      KeyPolicy:
        Version: "2012-10-17"
        Id: "Id-Kms-Replica-1"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: "Permitir el uso con RDS"
            Effect: "Allow"
            Principal:
              Service: "rds.amazonaws.com"
            Action:
              - "kms:CreateGrant"
              - "kms:ListGrant"
              - "kms:RevokeGrant"
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"
          - Sid: "Permitir a la funcion lambda del uso de la llave"
            Effect: "Allow"
            Principal:
              AWS: !Ref LambdaExecutionRoleArn
            Action:
              - "kms:CreateGrant"
              - "kms:ListGrant"
              - "kms:RevokeGrant"
              - "kms:DescribeKey"
              - "kms:Encrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"
            Condition: { "Bool": { "kms:GrantIsForAWSResource": true } }
Outputs:
  PrincipalKmsKeyReplicaArn:
    Value: !GetAtt PrincipalKmsKeyReplica.Arn
    Description: "The ARN of the KMS Key Replica for RDS snapshots in us- east-2"
